### ISSUE TITLE
Error on radial key press

### ISSUE THREAD

**Issue by Elite-Firesky** [Poltergeistzx/pzVehicleWorkshop#1]
STACK TRACE
-----------------------------------------
function: triggerEvent -- file: !_pzVehicleWorkshop_Init.lua line # 112 | MOD: Vehicle Workshop
function: showRadialMenu -- file: VehicleMenu.lua line # 71 | MOD: Vehicle Workshop
function: onKeyStartPressed -- file: ISUIHandler.lua line # 52 | Vanilla

Happening when radial menu key is pressed outside and away from the vehicle, possible incompatibility with Better Towing mod? As it might have only started happening after adding the mod.

**Comment by Poltergeist-ix** [comment]
I will test it later, do you have a full stack trace?

I am able to replicate this when I change the Toggle UI hotkey.

**Comment by Elite-Firesky** [comment]
I'll test it now and see if it still happens, I'll post full trace if it does.

**Comment by Elite-Firesky** [comment]
LOG  : General     , 1699215944654> 4,650,742> -----------------------------------------
STACK TRACE
-----------------------------------------
function: triggerEvent -- file: !_pzVehicleWorkshop_Init.lua line # 112 | MOD: Vehicle Workshop
function: showRadialMenu -- file: VehicleMenu.lua line # 71 | MOD: Vehicle Workshop
function: onKeyStartPressed -- file: ISUIHandler.lua line # 52 | Vanilla

ERROR: General     , 1699215944655> 4,650,742> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: getScriptName of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1699215944655> 4,650,742> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: getScriptName of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.input.GameKeyboard.update(GameKeyboard.java:106)
	at zombie.GameWindow.logic(GameWindow.java:249)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Poltergeist-ix** [comment]
How did you test? Did you download the fix and make sure that mod version was enabled?

**Comment by Elite-Firesky** [comment]
Correct, I have a private mod I use where I overwrite other mods for tweaks and minor fixes, so I don't have to make direct changes to the files, so I used that with your updated file from GitHub, however I had a typo in my folder structure.. I can confirm it's now working without any errors.
